### ISSUE TITLE
"timeoutable" function is public but not exported, breaking selenium_youtube

### ISSUE THREAD

**Issue by marcosdly** [kkristof200/py_kstopit#2]
I was trying to use [selenium_youtube](https://github.com/kkristof200/selenium_youtube) to make uploads and instantly got this error:

```
Traceback (most recent call last):
  File "/home/marcosdly/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/marcosdly/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/marcosdly/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/marcosdly/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/marcosdly/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/marcosdly/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/marcosdly/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/marcosdly/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/marcosdly/my-git-repos/yt-shorts/src/main.py", line 5, in <module>
    from video_posting_thread import watch_db_and_post_video
  File "/home/marcosdly/my-git-repos/yt-shorts/src/video_posting_thread.py", line 8, in <module>
    from youtube_api import login as yt_login, post_video_youtube
  File "/home/marcosdly/my-git-repos/yt-shorts/src/youtube_api.py", line 2, in <module>
    from selenium_youtube import Youtube
  File "/home/marcosdly/my-git-repos/yt-shorts/.venv/lib/python3.10/site-packages/selenium_youtube/__init__.py", line 1, in <module>
    from .youtube import Youtube
  File "/home/marcosdly/my-git-repos/yt-shorts/.venv/lib/python3.10/site-packages/selenium_youtube/youtube.py", line 15, in <module>
    from kstopit import timeoutable, TimeoutType
ImportError: cannot import name 'timeoutable' from 'kstopit' (/home/marcosdly/my-git-repos/yt-shorts/.venv/lib/python3.10/site-packages/kstopit/__init__.py)
```

It uses a function called `timeoutable` that, I checked it out, is said to be public, but it's not exported.

#### Versions:
- `kstopit`: 0.0.11
- `selenium_youtube`: 2.0.29

**Comment by marcosdly** [comment]
#3 fix

**Comment by kkristof200** [comment]
Merged it. Thanks!
